AWS_ACCESS_KEY: AKIAXGDFPWGWZRYALSVU
AWS_SECRET_KEY: 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
AWS_BUCKET: michael-w-bucket
AWS_REGION: us-east-1

SECRET_KEY: sk_test_jLdce2zVVm8QnrAlA3Bz9BOe00c23b39Aw
PUBLISHABLE_KEY: pk_test_gBTYcEi98HGfwQnMCE08p6Jj006KjXfcs0