AWS_ACCESS_KEY: AKIAXGDFPWGW2UYUP6EB
AWS_SECRET_KEY: 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
AWS_BUCKET: michael-w-bucket
AWS_REGION: us-east-1

SECRET_KEY: sk_test_jLdce2zVVm8QnrAlA3Bz9BOe00c23b39Aw
PUBLISHABLE_KEY: pk_test_gBTYcEi98HGfwQnMCE08p6Jj006KjXfcs0